# Topic: More Data Types

## Python Concepts: 
* list processing
* arrays

### Keywords


### Data Types
* <code>numpy array (ndarray)</code>

### Built-In functions:


### Methods:
* <code><i>numpy</i>.array</code>
* <code><i>numpy</i>.zeros</code>
* <code><i>numpy</i>.shape</code>
* <code><i>numpy</i>.add</code>
* <code><i>numpy</i>.dot</code>
* <code><i>numpy</i>.concatenate</code>


### Modules:
* <code>numpy</code>


<hr>

<u><b>EXERCISES:</b></u>
      <br>

[Filling Lists](#filling_lists)

[Linear Algebra](#linear_algebra)

>[Matrices as Lists of Lists](#matrices_as_list_of_lists)
        <br>
                >>[Create Matrices](#create_matrices) <br>
                >>[Dimensions](#dimensions) <br>
                >>[Matrix Addition](#matrix_addition) <br>
                >>[Matrix Multiplication](#matrix_multiplication) <br>
                >>>[Multiplication - first element](#matrix_multiplication_first_element) <br>
                >>>[Multiplication - second element](#matrix_multiplication_second_element) <br>
                >>>[Multiplication - any specified element](#matrix_multiplication_any_specified_element) <br>
                >>>[Multiplication - all elements (1st option)](#matrix_multiplication_all_elements_1) <br>
                >>>[Multiplication - all elements (2nd option)](#matrix_multiplication_all_elements_2) <br>
        
>[Matrices as Arrays - using numpy](#matrices_as_arrays)
        <br>
                >>[Create Matrices](#create_matrices_arrays) <br>
                >>[Dimensions](#dimensions_arrays) <br>
                >>[Matrix Addition](#matrix_addition_arrays) <br>
                >>[Matrix Multiplication](#matrix_multiplication_arrays) <br>

[Noughts and crosses](#noughts_and_crosses)
<br>


[Wordle](#wordle)
   <br>

<hr>

<a name="filling_lists"><a>
    
<b>Q: Filling Lists</b>

In [2]:
# We wish to fill a list to contain the first 100 square numbers: [0, 1, 2, 4, 9, 16, 25 ...]
# It's too long to create manually, so we want to write a loop to create the list

# Why does the following code not work?

my_list = []
for i in range(100):
    my_list[i] = i * i
print(my_list)



IndexError: list assignment index out of range

In [1]:
# Rewrite the above code to incrementally append each element to the list, one by one

# WRITE YOUR ANSWER HERE


In [2]:
# Rewrite the above code to create a list of size 100 where each element is 0

# WRITE YOUR ANSWER HERE


In [5]:
# Another way of achieving the same result is as follows:
zeros = [0] * 100
print(zeros)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [3]:
# Rewrite your code to compute the first 100 square numbers, but this time first create a list of 100 elements 
# that all have the (non)value None
# (None is a Python keyword used to indicate a null value.)
# And then update the elements to their correct value inside the loop

# WRITE YOUR ANSWER HERE


In [4]:
# Another Python mechanism for achieving the same result is called a list comprehension), eg:

squares = [index * index for index in range(100)]
print(squares)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676, 729, 784, 841, 900, 961, 1024, 1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849, 1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916, 3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225, 4356, 4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776, 5929, 6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569, 7744, 7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604, 9801]


In [5]:
# Use a list comprehension to create a list of 100 numbers where each element is 0

# WRITE YOUR ANSWER HERE


In [6]:
# Use a list comprehension to create a list of consecutive integer numbers from 0 to 99

# WRITE YOUR ANSWER HERE


Note: the for loop used in a list comprehension needn't be a simple range loop.

<a name="linear_algebra"></a>

# Linear Algebra

https://en.wikipedia.org/wiki/Linear_algebra

Linear algebra requires us to represent vectors and matrices.

In this tutorial we will explore two different ways of representing Matrices in Python:
1. As a <code>list</code> of <code>list</code>s
2. As a <code>numpy</code> 2-dimensional <code>array</code>

We will also consider two different ways of performing matrix and vector operations:
1. Using high-level <code>numpy</code> functions
2. Implemented ourselves using loops that access individual elements of <code>list</code>s and <code>array</code>s

Clearly, using high-level <code>numpy</code> functions is simplier and more efficient, but there will be times when the operation we wish to perform is not available via a high-level library, so we need the programming skills to be able to implement any operation using primitive element-wise operations and loops. 


<a name="matrices_as_list_of_lists"></a>
# Matrices as <code>list</code>s of <code>list</code>s</b>

<a name= "create_matrices">
<b>Q: Create Matrices</b>

Represent the following matrices in Python as <code>list</code>s of <code>list</code>s:

$$
first = \begin{bmatrix} 
1 & 2 & 3 \\
4 & 5 & 6 
\end{bmatrix},
second = \begin{bmatrix} 
10 & 11 & 12 \\
13 & 14 & 15 
\end{bmatrix}
$$

In [10]:
# WRITE YOUR ANSWER HERE


<a name= "dimensions"></a>
<b>Q: Dimensions</b><br>

Write a function to compute the dimensions of a matrix represented as a <code>list</code> of <code>list</code>s.

The function should return a <code>tuple</code> that contains the number of <b>rows</b> and number of <b>columns</b> in the given matrix.

In [11]:
# Return the row and column dimensions of the given matrix
def dimensions(matrix):
    
    # WRITE YOUR ANSWER HERE


#---------------------------------------------------------
# These are the tests your function must pass.

""" 
>>> dimensions(first)  # Test 1 - using example above
(2, 3)

>>> dimensions(second)  # Test 2 - using example above
(2, 3)

>>> dimensions([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])  # Test 3
(2, 5)

>>> dimensions([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])  # Test 4
(5, 2)

"""

#---------------------------------------------------------
# This main program executes all the tests above when this
# code is run.  Comment out the code below if you do not want
# to run the tests automatically.

from doctest import testmod
print(testmod(verbose = False))

TestResults(failed=0, attempted=4)


<a name = "matrix_addition"></a>

<b>Q: Matrix Addition</b>
<br>

Write a function that adds together two matrices.

The result for the above two matrices should be:

$$\begin{bmatrix} 
11 & 13 & 15 \\
17 & 19 & 21 
\end{bmatrix}
$$

Use the <code>dimensions</code> function above in your solution.

You can also assume that the two matrices provided as input have the same dimensions. You can check that by using the following Python code:

<code>assert dimensions(matrix_a) == dimensions(matrix_b)</code>

In [12]:
# Return a matrix as the result of adding
# two given matrices
def matrix_add(matrix_a, matrix_b):
    assert dimensions(matrix_a) == dimensions(matrix_b)
    
    # WRITE YOUR ANSWER HERE

    
    
#---------------------------------------------------------
# These are the tests your function must pass.

""" 
>>> matrix_add(first, second)  # Test 1 - using example above
[[11, 13, 15], [17, 19, 21]]


>>> matrix_add([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], [[11, 12, 13, 14, 15], [16, 17, 18, 19, 20]])  # Test 2
[[12, 14, 16, 18, 20], [22, 24, 26, 28, 30]]


>>> matrix_add([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]], [[1, 1], [1, 1], [1, 1], [1, 1], [1, 1]])  # Test 3
[[2, 3], [4, 5], [6, 7], [8, 9], [10, 11]]

"""

#---------------------------------------------------------
# This main program executes all the tests above when this
# code is run.  Comment out the code below if you do not want
# to run the tests automatically.

from doctest import testmod
print(testmod(verbose = False))

TestResults(failed=0, attempted=3)


<a name = "matrix_multiplication"></a>
<b>Q: Matrix Multiplication</b>
<br>

To add two matrices, they need to have the same dimensions.

To <i>multiply</i> two matrices, the number of columns of the first matrix must be the same as the number of rows in the second matrix.

So, if the first matrix has dimension ($rowsA$, $colsA$), and the second matrix has dimension ($rowsB$, $colsB$), then $colsA$ must equal $rowsB$ and the result will have dimension ($rowsA$, $colsB$).

So let's consider a new example that has those properties:

$$
matrix_1 = \begin{bmatrix} 
1 & 2 & 3 \\
4 & 5 & 6 
\end{bmatrix},
matrix_2 = \begin{bmatrix} 
10 & 11 \\
12 & 13 \\
14 & 15 \\
\end{bmatrix}
$$

Represent those matrices in Python as lists of lists:

In [13]:
# WRITE YOUR ANSWER HERE


<b>Q: Matrix Multiplication - first element</b>
<a name = "matrix_multiplication_first_element"></a>

In this case the result of multiplyng those two matrices will be:
$$matrix_1 \times matrix_2 = \begin{bmatrix} 
76 & 82 \\
184 & 199 \\
\end{bmatrix}
$$

Let's look at how this result is computed step by step (our algorithm will follow the same step by step proceedure).

Firstly, the value $76$ in the result matrix is computed based on the first row of $matrix_1$ and the first column of $matrix_2$ (highlighted in blue below):

$$matrix_1 \times matrix_2 = \begin{bmatrix} 
\color{blue}{76} & 82 \\
184 & 199 \\
\end{bmatrix}
$$

$$
matrix_1 = \begin{bmatrix} 
\color{blue} 1 & \color{blue}2 & \color{blue}3 \\
4 & 5 & 6 
\end{bmatrix},
matrix_2 = \begin{bmatrix} 
\color{blue}{10} & 11 \\
\color{blue}{12} & 13 \\
\color{blue}{14} & 15 \\
\end{bmatrix}
$$

- We multiply the $1$ (which is the <b>first</b> element of the first row in $matrix_1$) by $10$ (which is the <b>first</b> element of the first column in $matrix_2$),
we then add to that the result of 
- multiplying $2$ (which is the <b>second</b> element of the first row in $matrix_1$) by $12$ (which is the <b>second</b> element of the first column in $matrix_2$),
finally we add to that the result of
- multiplying  $3$ (which is the <b>third</b> element of the first row in $matrix_1$) by $14$ (which is the <b>third</b> element of the first column in $matrix_2$)
- to produce a grand total of $1 \times 10 + 2 \times 12 + 3 \times 14 = 76$. 

In [14]:
# We'll start by writing Python code to compute just that FIRST element of the result matrix

def matrix_multiply_element00(matrix_a, matrix_b):
    
    # check that the number of columns in first matrix is the same 
    # as the number of rows in the second matrix
    rows_a, cols_a = dimensions(matrix_a) # store each value of the tuple in a separate variable
    rows_b, cols_b = dimensions(matrix_b)
    assert cols_a == rows_b
    
    # WRITE YOUR ANSWER HERE

    
    
#---------------------------------------------------------
# These are the tests your function must pass.

""" 
>>> matrix_multiply_element00(matrix_1, matrix_2)  # Test 1 - using example above
76

>>> matrix_multiply_element00([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], [[2, 3], [4, 5], [6, 7], [8, 9], [10, 11]])  # Test 2
110

>>> matrix_multiply_element00([[1, 2], [3, 4]], [[5, 6], [7, 8]])  # Test 3
19

"""

#---------------------------------------------------------
# This main program executes all the tests above when this
# code is run.  Comment out the code below if you do not want
# to run the tests automatically.

from doctest import testmod
print(testmod(verbose = False))

TestResults(failed=0, attempted=3)


<b>Q: Matrix Mutltiplication - second element</b>
<a name = "matrix_multiplication_second_element"></a>

Next we move on to computing the result $82$ that appears in the second column of the first row of the result matrix.
This is computed based on the first row of matrix $x$ and the <b>second</b> column of matrix $y$ (highlighted in blue below):

$$matrix_1 \times matrix_2 = \begin{bmatrix} 
{76} & \color{blue}{82} \\
184 & 199 \\
\end{bmatrix}
$$

$$
matrix_1 = \begin{bmatrix} 
\color{blue} 1 & \color{blue}2 & \color{blue}3 \\
4 & 5 & 6 
\end{bmatrix},
matrix_2 = \begin{bmatrix} 
{10} & \color{blue}{11} \\
{12} & \color{blue}{13} \\
{14} & \color{blue}{15} \\
\end{bmatrix}
$$
 
- We multiply the  1  (which is the <b>first</b> element of the first row in matrix_1) by  11  (which is the <b>first</b> element of the second column in matrix_2), we then add to that the result of
- multiplying  2  (which is the <b>second</b> element of the first row in matrix_1) by  13  (which is the <b>second</b> element of the second column in matrix_2), finally we add to that the result of
- multiplying  3  (which is the <b>third</b> element of the first row in matrix_1) by  15  (which is the <b>third</b> element of the second column in matrix_2)
- to produce a grand total of  1×11+2×13+3×15=82.

In [15]:
# Make a copy of that code, and alter it to compute just that SECOND element 
# of the first row of the result matrix

def matrix_multiply_element01(matrix_a, matrix_b):
    
    # check that the number of columns in first matrix is the same 
    # as the number of rows in the second matrix
    rows_a, cols_a = dimensions(matrix_a) # store each value of the tuple in a separate variable
    rows_b, cols_b = dimensions(matrix_b)
    assert cols_a == rows_b
 
    # WRITE YOUR ANSWER HERE

    

#---------------------------------------------------------
# These are the tests your function must pass.

""" 
>>> matrix_multiply_element01(matrix_1, matrix_2)  # Test 1 - using example above
82

>>> matrix_multiply_element01([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], [[2, 3], [4, 5], [6, 7], [8, 9], [10, 11]])  # Test 2
125

>>> matrix_multiply_element01([[1, 2], [3, 4]], [[5, 6], [7, 8]])  # Test 3
22

"""

#---------------------------------------------------------
# This main program executes all the tests above when this
# code is run.  Comment out the code below if you do not want
# to run the tests automatically.

from doctest import testmod
print(testmod(verbose = False))

TestResults(failed=0, attempted=3)


<b>Q: Matrix Mutltiplication - any specified element</b>
<a name = "matrix_multiplication_any_specified_element"></a>

In [16]:
# Make a copy of that code and now generalize it code by adding 
# parameters for the row and col positions of the result matrix
def matrix_multiply_element(matrix_a, matrix_b, row, column):
    
    # check that the number of columns in first matrix is the same 
    # as the number of rows in the second matrix
    rows_a, cols_a = dimensions(matrix_a) # store each value of the tuple in a separate variable
    rows_b, cols_b = dimensions(matrix_b)
    assert cols_a == rows_b
 
    # WRITE YOUR ANSWER HERE


#---------------------------------------------------------
# These are the tests your function must pass.

""" 
>>> matrix_multiply_element(matrix_1, matrix_2, 0, 0)  # Test 1 - using example above
76

>>> matrix_multiply_element(matrix_1, matrix_2, 0, 1)  # Test 2 - using example above
82

>>> matrix_multiply_element(matrix_1, matrix_2, 1, 0)  # Test 3 - using example above
184

>>> matrix_multiply_element(matrix_1, matrix_2, 1, 1)  # Test 4 - using example above
199

>>> matrix_multiply_element([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], [[2, 3], [4, 5], [6, 7], [8, 9], [10, 11]], 0, 0)  # Test 5
110

>>> matrix_multiply_element([[1, 2], [3, 4]], [[5, 6], [7, 8]], 0, 1)  # Test 6
22

"""

#---------------------------------------------------------
# This main program executes all the tests above when this
# code is run.  Comment out the code below if you do not want
# to run the tests automatically.

from doctest import testmod
print(testmod(verbose = False))

TestResults(failed=0, attempted=6)


<b>Q: Matrix Mutltiplication - all elements (1st option)</b>
<a name = "matrix_multiplication_all_elements_1"></a>

In [17]:
# Now implement matrix multipy by calling your matrix_multiply_element function to compute each element of the result
# Hint: it will be very similar to your matrix_add function above

def matrix_multiply(matrix_a, matrix_b):

    # check that the number of columns in first matrix is the same 
    # as the number of rows in the second matrix
    rows_a, cols_a = dimensions(matrix_a) # store each value of the tuple in a separate variable
    rows_b, cols_b = dimensions(matrix_b)
    assert cols_a == rows_b
 
    # WRITE YOUR ANSWER HERE


#---------------------------------------------------------
# These are the tests your function must pass.

""" 
>>> matrix_multiply(matrix_1, matrix_2)  # Test 1 - using example above
[[76, 82], [184, 199]]


>>> matrix_multiply([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], [[2, 3], [4, 5], [6, 7], [8, 9], [10, 11]])  # Test 2
[[110, 125], [260, 300]]

>>> matrix_multiply([[1, 2], [3, 4]], [[5, 6], [7, 8]])  # Test 3
[[19, 22], [43, 50]]


"""

#---------------------------------------------------------
# This main program executes all the tests above when this
# code is run.  Comment out the code below if you do not want
# to run the tests automatically.

from doctest import testmod
print(testmod(verbose = False))

TestResults(failed=0, attempted=3)


<b>Q: Matrix Mutltiplication - all elements (2nd option)</b>
<a name = "matrix_multiplication_all_elements_2"></a>

In [18]:
# Now create a new version of your function that incorporates the code from matrix_multiply_element 
# directly into your matrix_multiply function 
# (rather than *calling* the matrix_multiply_element function).
# Your new function should now have triply nested for loops. 

def matrix_multiply_combined(matrix_a, matrix_b):
    
    # check that the number of columns in first matrix is the same 
    # as the number of rows in the second matrix
    rows_a, cols_a = dimensions(matrix_a) # store each value of the tuple in a separate variable
    rows_b, cols_b = dimensions(matrix_b)
    assert cols_a == rows_b

    # WRITE YOUR ANSWER HERE


#---------------------------------------------------------
# These are the tests your function must pass.

""" 
>>> matrix_multiply_combined(matrix_1, matrix_2)  # Test 1 - using example above
[[76, 82], [184, 199]]


>>> matrix_multiply_combined([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], [[2, 3], [4, 5], [6, 7], [8, 9], [10, 11]])  # Test 2
[[110, 125], [260, 300]]

>>> matrix_multiply_combined([[1, 2], [3, 4]], [[5, 6], [7, 8]])  # Test 3
[[19, 22], [43, 50]]


"""

#---------------------------------------------------------
# This main program executes all the tests above when this
# code is run.  Comment out the code below if you do not want
# to run the tests automatically.

from doctest import testmod
print(testmod(verbose = False))

TestResults(failed=0, attempted=3)


In [ ]:
# Which of these two versions do you prefer? Why?


# NumPy
<a name = "matrices_as_arrays"></a>

Next we explore using the <code>numpy</code> library to represent matrices.

In [19]:
# When using the NumPy module, we can create a 2-D array of zeros as follows:
import numpy

list_of_zeros = numpy.zeros((10,10))
print(list_of_zeros)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


<b>Q: Create Matrices - arrays</b>
<a name = "create_matrices_arrays"></a>

Represent the following matrices in Python code as NumPy arrays

$$
matrix_3 = \begin{bmatrix} 
1 & 2 & 3 \\
4 & 5 & 6 
\end{bmatrix},
matrix_4 = \begin{bmatrix} 
10 & 11 & 12 \\
13 & 14 & 15 
\end{bmatrix}
$$

In [20]:
import numpy

# WRITE YOUR ANSWER HERE


<b>Q: Dimensions - arrays</b>
<a name = "dimensions_arrays"></a>

How do we compute the equivalent of our dimensions function for NumPy arrays?

Hint: https://numpy.org/doc/stable/reference/generated/numpy.shape.html#numpy.shape

In [21]:
# Find the dimensions of the new matrices

# WRITE YOUR ANSWER HERE


(2, 3)

<b>Q: Matrix Addition - arrays</b>
<a name = "matrix_addition_arrays"></a>

In [22]:
# Add together matrix_3 and matrix_4 using the NumPy add function

# WRITE YOUR ANSWER HERE


array([[11, 13, 15],
       [17, 19, 21]])

In [23]:
# Or, even more simply ...
matrix_3 + matrix_4

array([[11, 13, 15],
       [17, 19, 21]])

<b>Q: Matrix Multiplication - arrays</b>
<a name = "matrix_multiplication_arrays"></a>

For matrix multiply, let's use this example:

$$
matrix_5 = \begin{bmatrix} 
1 & 2 & 3 \\
4 & 5 & 6 
\end{bmatrix},
matrix_6 = \begin{bmatrix} 
10 & 11 \\
12 & 13 \\
14 & 15 \\
\end{bmatrix}
$$

Now create new <code>numpy</code> arrays:

In [24]:
# WRITE YOUR ANSWER HERE


(2, 3)

In [25]:
# matrix multiplication can be done simply by using the numpy dot function

numpy.dot(matrix_5, matrix_6)


array([[ 76,  82],
       [184, 199]])

Or we could do it the hard way and compute matrix multiply ourselves, element by element, as we did above.

Make a copy of your <code>matrix_multiply_combined</code> function so that it operates on <code>numpy array</code>s rather than <code>list</code>s of <code>list</code>s

In [26]:

def matrix_multiply_arrays(matrix_a, matrix_b):
    
    # check that the number of columns in first matrix is the same 
    # as the number of rows in the second matrix
    rows_a, cols_a = matrix_a.shape # store each value of the tuple in a separate variable
    rows_b, cols_b = matrix_b.shape
    assert cols_a == rows_b

    # WRITE YOUR ANSWER HERE

    
#---------------------------------------------------------
# These are the tests your function must pass.

""" 
>>> matrix_multiply_arrays(matrix_5, matrix_6)  # Test 1 - using example above
[[76, 82], [184, 199]]


>>> matrix_multiply_arrays(numpy.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]), numpy.array([[2, 3], [4, 5], [6, 7], [8, 9], [10, 11]]))  # Test 2
[[110, 125], [260, 300]]

>>> matrix_multiply_arrays(numpy.array([[1, 2], [3, 4]]), numpy.array([[5, 6], [7, 8]]))  # Test 3
[[19, 22], [43, 50]]


"""

#---------------------------------------------------------
# This main program executes all the tests above when this
# code is run.  Comment out the code below if you do not want
# to run the tests automatically.

from doctest import testmod
print(testmod(verbose = False))

TestResults(failed=0, attempted=3)


In [27]:
# What was the main difference?


<a name="noughts_and_crosses"><a>
    
<b>Q: Noughts and Crosses</b>
    
As an exercise in processing data stored in arrays (<code>numpy</code>'s multidimensional 
container of items: <code>ndarray</code>), here you are required to write several small code segments that extract data stored in arrays both by value and position.

Recall that the children's game of Noughts and Crosses (US:
Tic-Tac-Toe) is played on a 3 x 3 matrix in which the cells
may be empty '_', a cross 'X' or a nought 'O' (actually, the letter O).  
    
<img src = "Noughts_and_Crosses.png">    

Such a matrix can be represented using an array containing three
rows, each of which is an array containing three values.

Below are the outcomes of four games of Noughts and Crosses.
represented as lists. Games 1 and 2 have been represented as
a single <code>ndarray</code> and Games 3 and 4 have been represented
as three separate <code>ndarray</code>s.

For each game there is a series of challenges for you to solve by printing appropriate values extracted from the arrays.  Note that all of these can be solved with just a
few lines of Python code.  In all cases you must use <code>for</code> loops to solve the problem.


In [28]:
# import the numpy module, and rename it as 'np'
import numpy as np

# Author: Colin Fidge 2021

#----------------------------------------------------------------#
# Very easy: Using a FOR loop, print the three rows in
# Game 1, all on one line.  Your code should print:
#
#     ['X', 'O', 'X'] ['X', 'X', 'O'] ['O', 'O', 'O']
#
# Remember that using parameter "end = ''" at the end of a
# call to a PRINT function prevents it from printing a newline.

# Game 1 - Noughts win
game_1 = np.array([['X', 'O', 'X'],
                 ['X', 'X', 'O'],
                 ['O', 'O', 'O']])
print("game_1:")

# WRITE YOUR ANSWER HERE



game_1:
['X' 'O' 'X']['X' 'X' 'O']['O' 'O' 'O']



In [29]:
#----------------------------------------------------------------#
# Easy: Using a FOR loop, print the values of all cells
# in Game 2, all on one line.  Your code should print:
#
#     OXOXXXOOX
#
# Hint: You will need two FOR loops.

# Game 2 - Crosses win
#
game_2 =  np.array([['O', 'X', 'O'],
                   ['X', 'X', 'X'],
                   ['O', 'O', 'X']])

print("game_2:")

# WRITE YOUR ANSWER HERE



game_2:
OXOXXXOOX



In [30]:
#----------------------------------------------------------------#
# Medium difficulty: Write a FOR loop to print all
# the cells in Game 3, row by row, from top to bottom.
# Your code should print:
#
#    XOXXOOOXX
#
# Hint: 
# You can do this with just a single FOR
# loop by "adding" the separate arrays together using the
# numpy function: 
#     concatenate

# Game 3 - It's a tie
#
game_3a = np.array(['X', 'O', 'X'])
game_3b = np.array(['X', 'O', 'O'])
game_3c = np.array(['O', 'X', 'X'])

print("game_3:")

# WRITE YOUR ANSWER HERE



game_3:
XOXXOOOXX



In [31]:
#----------------------------------------------------------------#
# Medium difficulty: Write FOR-EACH code to print the cells
# on the diagonal from top-left to bottom-right for Game 4.
# Your code should print:
#
#    XXO
#
# Hint: You could use a numeric loop variable to keep
# track of the position of each cell to be printed.

# Game 4 - Noughts win
#
game_4 = np.array([['X', 'O', 'X'],
                  ['X', 'X', 'O'],
                  ['X', 'O', 'O']])

print("game_4:")

# WRITE YOUR ANSWER HERE



game_4:
XXO



In [32]:
#----------------------------------------------------------------#
# A bit harder: Write a FOR loop to print the cells
# in Game 4 by columns, rather than rows.  In other
# words, you must print the first element from each of
# the three rows, then the second, then the third.
# Your code should print:
#
#   XO__XO_OX
# 
# Hint: You could use a numeric loop variable to keep
# track of the column; and slicing to get the value
# from each row at that column
#
# Game 5 - Crosses wins easily

game_5 = np.array([['X', '_', '_'],
                 ['O', 'X', 'O'],
                 ['_', 'O', 'X']])

print("game_5:")

# WRITE YOUR ANSWER HERE


game_5:
XO__XO_OX



# Wordle
<a name = "wordle"></a>

In this exercise we are going to learn about the Python Dictionary type. We are also going to learn how large complex programs can be created by using user defined functions, each of which is very simple and conceptually does only one thing. Such functions may be built from other functions. We will also learn how such programs can be constructed in an <i>interative and incremental manner</i> - developing simple functions and testing that they work before proceeding to use them to build other functions.

The exercise will be based on a well known Internet based game called 'Wordle' which was acquired by the New York times after it went viral: https://www.nytimes.com/games/wordle

### Wordle Rules

The object of the game is to guess a randomly selected 5 letter word. The system responds to your guesses by indicating for each letter of the word that you guess whether it is:
- the correct letter in the correct position, 
- a letter that exists within the secret word, but not at the correct position, or
- the letter is not in the secret word at all.

Only valid 5-letter words are allowed to be entered as guesses.

## Read all words

We need to start with every possible 5 letter word in the English dictionary.
We have provided you with a file <code>words.txt</code> that contains a complete list of such words.
You need to load that file and generate a list of words. Each word will be a Python string.

- Use the built in Python open function to <code>open</code> the file named "words.txt".
- Use the <code>read()</code> method of the opened file to read its contents.
- Note, it is good practice to always call the <code>close()</code> method of the file once you've finished reading from it.
- Examine the contents to see what it contains

In [33]:
file_open = open('words.txt')
contents = file_open.read()
file_open.close()
len(contents) # should be 77831

77831

In [34]:
# Next we will call the splitlines() method of the content string to convert it to a list of strings, one for each line in the file.
# Store the resulting list in a variable so that we can use it later.

words = contents.splitlines()
len(words)
# Examine the list to see what it contains
#print(words)

12972

## Randomly choose secret word

In [35]:
# Write a function that will randomly select a secret word from the list of all words.
# Use the random.randrange function to select a random index position to select the secret word from.
# Store the secret word in a global variable, so that we can use it later.
# You can call this function whenever you want to start a new game.

import random

def new_game():
    global secret
    
    # WRITE YOUR ANSWER HERE
    index = random.randrange(len(words))
    secret = words[index]


In [38]:
# test that it works as expected
new_game()
secret

'bozos'

## Cheat

In [39]:
# Write a function which allows us to cheat (for testing purposes).
# It should print: 'The answer is ' ...

def cheat():
    # WRITE YOUR ANSWER HERE
    print(f"The answer is {secret}")

In [40]:
# test that it works as expected
cheat()

The answer is bozos


# Is valid word?

Only valid words in the English dictionary can be used as guesses. Write a function to check that the guess is a real word.

In [41]:
# Given a guessed word, return True if the word is contained
# in the list of all words
# otherwise, print the message: ...' is not a valid word' 
def is_valid_word(guess):
    
    # WRITE YOUR ANSWER HERE
    if guess in words:
        return True
    else:
        print("{0} is not a valid word".format(guess))

#---------------------------------------------------------
# These are the tests your function must pass.

""" 
>>> is_valid_word('tears')  # Test 1 - valid word
True

>>> is_valid_word('sedan')  # Test 2 - valid word
True

>>> is_valid_word('audio')  # Test 3 - valid word
True

>>> is_valid_word('zzzzz')  # Test 4 - invalid word
zzzzz is not a valid word


"""

#---------------------------------------------------------
# This main program executes all the tests above when this
# code is run.  Comment out the code below if you do not want
# to run the tests automatically.

from doctest import testmod
print(testmod(verbose = False))

TestResults(failed=0, attempted=4)


## Test Letters

Next we move on to the main step of determining which letters match.

We start by doing this for just one letter at a particular position

In [54]:
# Write a function that takes a letter guessed and its position (between 0 and 4)
# and returns 'correct' if the letter matches the secret word at the specified position,
# returns 'present' if the letter is present in the secret word, but not at the specified position,
# otherwise returns 'wrong'

def check_letter(letter_guess, position):
    
    # WRITE YOUR ANSWER HERE
    
    if letter_guess == secret[position]:
        return 'correct'
    elif letter_guess in secret:
        return 'present'
    else:
        return 'wrong'

#---------------------------------------------------------
# These are the tests your function must pass.

# reset the secret word for testing
secret = 'track'

""" 
>>> check_letter('t', 0)  # Test 1
'correct'

>>> check_letter('d', 1)  # Test 2
'wrong'

>>> check_letter('k', 2)  # Test 3
'present'


"""

#---------------------------------------------------------
# This main program executes all the tests above when this
# code is run.  Comment out the code below if you do not want
# to run the tests automatically.

from doctest import testmod
print(testmod(verbose = False))


TestResults(failed=0, attempted=3)


## Guess prototype

Next we will create a simple prototype of the main part of the game were the user is allowed to make a guess and receive feedback.
For each letter in the guess, we will need to print the letter as well as indicate whether it is correct, present or wrong.

For example if the secret word is 'track' and the guessed word is 'trail' then the output might be:
<pre>
t correct
r correct
a correct
i wrong
l wrong
</pre>

In [56]:
# Given a guessed word, if it is a valid word, print each of the letters in the word, 
# together with an indication of whether the guessed letter is correct, present or wrong.
def guess(word) :

    # WRITE YOUR ANSWER HERE
    
    if is_valid_word(word):
        # each character position in the word
        for index in range(len(word)):
            # print the character
            print(word[index], end = ' ')
            # print if it is correct, present or wrong
            print(check_letter(word[index], index))
        

In [57]:
# Try playing the game by making a sequence of calls to the guess function until you guess all letters correctly.
guess('trail')

t correct
r correct
a correct
i wrong
l wrong


## OPTIONAL CHALLENGE - Display HTML

For those wishing to continue with this exercise, we will now convert the output into a more user friendly HTML output format where each correct, present or wrong letter is indicated via a color code: <span style='background-color:#6aaa64; color: white'>green</span> for correct, <span style='background-color:#c9b458; color: white'>yellow</span> for present and <span style='background-color:#787c7e; color: white'>grey</span> for wrong

In [58]:
# To display HTML strings within Jupyter we will use the IPython.core.display.HTML function
import IPython

def display(html) :
    return IPython.core.display.HTML(html) 

In [59]:
# Test that it works as expected, e.g.:
display('<b>Hello</b>')

## Generate HTML

Next we want to generate HTML for just one letter of the guessed word.

In [60]:
# Write a function that returns the following HTML string:
# <div style='background-color:red;width: 20px; height: 20px; color:white; margin: 1px; line-height: 20px; display:inline-block; text-align:center'>T</div>
# Note that the string contains single quotes '', so you'll need to use double quotes "" to create the string to return

def generate_div():
    
    # WRITE YOUR ANSWER HERE
    return "<div style='background-color:red;width: 20px; height: 20px; color:white; margin: 1px; line-height: 20px; display:inline-block; text-align:center'>T</div>"
    

In [61]:
# Test that it works as expected.
# The function itself should return a HTML formatted string, 
# but you can then pass that string to your display function to display it in a graphical manner.
display(generate_div())

In [62]:
# Next we will alter the generate_div function, so that it now takes two parameters, a color and a letter.
# The colour should replace "red" in the hard coded string above and the letter should replace the "T" between the tags.
# Use a Python f-String to insert the new values into the formated string.
# Make sure the letter is displayed in upper case.

def generate_div(letter, colour):
    
    # WRITE YOUR ANSWER HERE
    return f"<div style='background-color:{colour};width: 20px; height: 20px; color:white; margin: 1px; line-height: 20px; display:inline-block; text-align:center'>{letter.upper()}</div>"


In [63]:
# Use the display function to help test that it works as expected
display(generate_div('B', 'green'))

## Guess One Letter

In [64]:
# We may wish to change the actual colours used later, so we store them in a dictionary that we can lookup.
# Create a dictionary containing three values so that:

# colourChoices['correct']  will return '#6aaa64'
# colourChoices['present']  will return '#c9b458'
# colourChoices['wrong']    will return '#787c7e'

# WRITE YOUR ANSWER HERE to create your dictionary ...
colourChoices = {'correct':'#6aaa64', 
                 'present':'#c9b458',
                 'wrong': '#787c7e'}

# test
colourChoices['wrong']
colourChoices['correct']
colourChoices['present']



'#c9b458'

In [65]:
# Write a function that will take a guessed letter and position as parameters and 
# returns the colour coded HTML response string for just that one letter

def generate_letter(letter, position):
    
    # WRITE YOUR ANSWER HERE
    colour = colourChoices[check_letter(letter, position)]
    
    # alternatively:
    # result = check_letter(letter, position)
    # colour = colourChoices[result]
    
    return generate_div(letter, colour)
    

In [66]:
# Use your display function to test that it behaves as expected.
# E.g. 
secret = 'taisq'
display(generate_letter('t', 1)) 
# Should return a T with a mustard coloured background

## Allow Guesses

In [67]:
# Update your guess function to display the responses in HTML format ...

def guess(word) :

    # WRITE YOUR ANSWER HERE
    
    if is_valid_word(word):
        html = ''
        
        # each character position in the word
        for index in range(len(word)):
            html += generate_letter(word[index], index)
        return(display(html))


In [68]:
cheat()

The answer is taisq


In [69]:
# Test that it works as expected:
guess('trail')

The output should look something like this:

<div style='background-color:#6aaa64;width: 20px; height: 20px; color:white; margin: 1px; line-height: 20px; display:inline-block; text-align:center'>T</div>
<div style='background-color:#787c7e;width: 20px; height: 20px; color:white; margin: 1px; line-height: 20px; display:inline-block; text-align:center'>R</div>
<div style='background-color:#c9b458;width: 20px; height: 20px; color:white; margin: 1px; line-height: 20px; display:inline-block; text-align:center'>A</div>
<div style='background-color:#c9b458;width: 20px; height: 20px; color:white; margin: 1px; line-height: 20px; display:inline-block; text-align:center'>I</div>
<div style='background-color:#787c7e;width: 20px; height: 20px; color:white; margin: 1px; line-height: 20px; display:inline-block; text-align:center'>L</div>

Your answer will of course depend on the secret word currently selected

In [70]:
# Try playing the game by making a sequence of calls to the guess function until you guess all letters correctly.