### Vector Add
$$\begin{bmatrix} 
1 \\
2 \\
3
\end{bmatrix}
 + 
\begin{bmatrix} 
3 \\
4 \\
5
\end{bmatrix}
= 
\begin{bmatrix} 
4 \\
6 \\
8
\end{bmatrix}
$$


In [ ]:
# index     0  1  2
vector_a = [1, 2, 3]
vector_b = [3, 4, 5]

# vector_sum = []
# vector_sum.append(vector_a[0] + vector_b[0])
# vector_sum.append(vector_a[1] + vector_b[1])
# vector_sum.append(vector_a[2] + vector_b[2])


def add_vectors(vector_1, vector_2):
    
    # new list for storing the result of addition
    vector_sum = []
    
    # iterate over list of indexes
    for index in range(len(vector_1)):
        # add the sum to the new vector
        vector_sum.append(vector_1[index] + vector_2[index])
        
    return vector_sum

add_vectors(vector_a, vector_b)


### Vector Multiply
$$\begin{bmatrix} 
1 \\
2 \\
3
\end{bmatrix}
 \times
\begin{bmatrix} 
3 \\
4 \\
5
\end{bmatrix}
= 
26
$$

$$\begin{bmatrix} 
2 \\
4 \\
6 \\
8
\end{bmatrix}
 \times
\begin{bmatrix} 
1 \\
3 \\
5 \\
7
\end{bmatrix}
= 
100
$$

In [ ]:
def multiply_vectors(vector_1, vector_2):
    
    # result of dot product of vectors
    product = 0
    
    # iterate over list of indexes
    for index in range(len(vector_1)):
        # add to the product
        product += (vector_1[index] * vector_2[index])
        
    return product

multiply_vectors(vector_a, vector_b)
multiply_vectors([2, 4, 6, 8], [1, 3, 5, 7]) # 100

### Matrix Add
$$\begin{bmatrix} 
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{bmatrix}
 + 
\begin{bmatrix} 
10 & 11 & 12 \\
13 & 14 & 15 \\
16 & 17 & 18
\end{bmatrix}
= 
\begin{bmatrix} 
11 & 13 & 15 \\
17 & 19 & 21 \\
23 & 25 & 27
\end{bmatrix}
$$


In [ ]:
matrix_a = [[1,  2,  3],
            [4,  5,  6],
            [7,  8,  9]]

matrix_b = [[10, 11, 12],
            [13, 14, 15],
            [16, 17, 18]]

# Add two matrices together
def add_matrices(matrix_1, matrix_2):
    
    # new list for storing the result of addition
    matrix_sum = []

    # for each row
    for row in range(len(matrix_1)):
        
        # create a result row
        new_row = []
    
        # iterate over list of indexes
        for column in range(len(matrix_1[0])):
            # add the sum to the new row
            new_row.append(matrix_1[row][column] + matrix_2[row][column])
            
        # append the new row to the new matrix
        matrix_sum.append(new_row)
        
    return matrix_sum

add_matrices(matrix_a, matrix_b)



### Matrix Multiply

$$\begin{bmatrix} 
1 & 2 & 3 \\
4 & 5 & 6 
\end{bmatrix}
 \times 
\begin{bmatrix} 
10 & 11 \\
12 & 13 \\
14 & 15 
\end{bmatrix}
= 
\begin{bmatrix} 
76 & 82 \\
184 & 199
\end{bmatrix}
$$


In [ ]:
matrix_c = [[1,  2,  3],
            [4,  5,  6]]

matrix_d = [[10, 11],
            [12, 13], 
            [14, 15]]

# Add two matrices together
def multiply_matrices(matrix_1, matrix_2):
    
    # Sanity check
    # Check that the number of columns in first matrix is the same
    # as the number of rows in the second matrix
    
    # new list for storing the result 
    matrix_product = []

    # for each of the indexes for the rows of the first matrix
    for row in range(len(matrix_1)):
        
        # create a result row
        new_row = []
    
        # for each of the indexes for the columns in the second matrix
        for column in range(len(matrix_2[0])):
            
            # accumulate the sum of the products
            total = 0
            
            # first value in matrix_1 row * first value in the matrix_2 column
            # second value in matrix_1 row * second value in the matrix_2 column
            # ...etc
            
            # add the sum to the new row
            new_row.append(total)
            
        # append the new row to the new matrix
        matrix_product.append(new_row)
        
    return matrix_product

multiply_matrices(matrix_c, matrix_d)


In [25]:
import numpy

my_array = numpy.array([1, 2, 3])
type(my_array)

second_array = numpy.array([[1, 2, 3], [4, 5, 6]])
second_array

second_array[0][1]
second_array[0, 1]


2

In [32]:
matrix_c = [[1,  2,  3],
            [4,  5,  6],
            [7,  8,  9]]

matrix_d = [[10, 11, 12],
            [13, 14, 15],
            [16, 17, 18]]

#matrix_c + matrix_d

matrix_e = numpy.array(matrix_c)
matrix_f = numpy.array(matrix_d)
#matrix_e + matrix_f


numpy.add(matrix_e, matrix_f)
numpy.dot(matrix_e, matrix_f)

matrix_g = numpy.array([[1, 2, 3], [4, 5, 6]])
matrix_h = numpy.array([[10, 11], [12, 13], [14, 15]])
numpy.dot(matrix_g, matrix_h)


array([[ 76,  82],
       [184, 199]])

### Matrix Multiply

$$\begin{bmatrix} 
1 & 2 & 3 \\
4 & 5 & 6 
\end{bmatrix}
 \times 
\begin{bmatrix} 
10 & 11 \\
12 & 13 \\
14 & 15 
\end{bmatrix}
= 
\begin{bmatrix} 
76 & 82 \\
184 & 199
\end{bmatrix}
$$


In [33]:
numpy.transpose(matrix_g)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [37]:
numpy.zeros((5, 3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [44]:
array_of_ones = numpy.ones((4, 6))
array_of_ones

array_of_ones[1, -1] = 99999
array_of_ones
array_of_ones[1, -1]


99999.0

In [48]:
# indexes of columns       0    1    2
calories = numpy.array([[900, 750, 1020],  # index 0 of rows
                        [300, 1000, 2700], #       1
                        [500, 700, 2100],  #       2
                        [400, 900, 1780],  #       3
                        [600, 1200, 1100], #       4
                        [575, 1150, 1900], #       5
                        [600, 1020, 1700]])#       6

# lookup the third row
calories[2]
calories[2, :]

# just the second column in the third row
calories[2, 1:2]

# all of the dinner values (3rd column)
calories[:,2]


array([1020, 2700, 2100, 1780, 1100, 1900, 1700])